name: Data Updater

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  update-data:
    name: Updating data
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6' ]
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          cd .. && git clone git@github.com:ammitto/data.git
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Update gems
        run: |
          sudo gem install bundler --force
          bundle install --jobs 4 --retry 3
      - name: Run specs
        run: |
          ruby adapter.rb
