name: Data Updater

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  update-data:
    name: Updating data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6' ]
    steps:
      - name: Preparing data repo
        uses: actions/checkout@master
        with:
          repository: ammitto/data
          path: data
      - uses: actions/checkout@master
      - name: Show directory structure
        shell: bash
        run: |
          cd .. && ls
          pwd
